---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A codebuild project.

Parameters:
  Project:
    Description: 'The project that these resources are for.'
    Type: 'String'
    Default: 'tc-test-gh-actions'
  GitHubRepoUrl:
    Type: 'String'
    Default: "https://github.com/timcooper314/automatic-disco.git"
  GitHubOAuthToken:
    Type: 'String'
    NoEcho: true

Resources:
  ArtifactS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Project}-artifacts-281121"
      Tags:
        - Key: Project
          Value: !Ref Project

  BuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Project}-build-project-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${Project}-build-project-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                  - iam:ListRoles
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - logs:*
                  - lambda:*
                  - cloudformation:*
                  - codebuild:*
                  - cloudwatch:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetAccessPoint
                  - s3:PutAccountPublicAccessBlock
                  - s3:ListAccessPoints
                  - s3:GetAccountPublicAccessBlock
                  - s3:ListAllMyBuckets
                  - s3:ListJobs
                  - s3:CreateJob
                  - s3:HeadBucket
                  - s3:GetBucketLocation
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObjectAcl
                  - s3:DeleteObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt ArtifactS3Bucket.Arn
                  - !Sub "${ArtifactS3Bucket.Arn}/*"
      Tags:
        - Key: Project
          Value: !Ref Project

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${Project}-build-proj"
      ServiceRole: !GetAtt BuildProjectRole.Arn
      TimeoutInMinutes: 10
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      Artifacts:
        Type: S3
        Location: !Ref ArtifactS3Bucket
        Path: "codebuild_artifacts"
        Name: "/"
        NamespaceType: BUILD_ID
      BadgeEnabled: true
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepoUrl
        Auth:
          Type: OAUTH
          Resource: !Ref GitHubOAuthToken
        ReportBuildStatus: true
       # BuildSpec:
#        BuildStatusConfig:
#          TargetUrl:
#          Context:
      Tags:
        - Key: Project
          Value: !Ref Project
