name: CodeBuild

on:
  push:
    branches:
      - master
      - update/gh-only

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: SAM Setup
      uses: aws-actions/setup-sam@v1
    - name: SAM Deploy
      run: |
        chmod +x deploy.sh
        ./deploy.sh
